name: 'Install Nix on ephemeral runners'
description: 'Installs Nix and sets up AWS credentials to push to the Nix binary cache'
inputs:
  push-to-cache:
    description: 'Whether to push build outputs to the Nix binary cache'
    required: false
    default: 'false'
  aws-region:
    description: 'AWS region for the Nix binary cache S3 bucket'
    required: false
    default: 'us-east-1'
runs:
  using: 'composite'
  steps:
    - name: aws-creds
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      if: ${{ inputs.push-to-cache == 'true' }}
      with:
        role-to-assume: ${{ env.DEV_AWS_ROLE }}
        aws-region: ${{ inputs.aws-region }}
        output-credentials: true
        role-duration-seconds: 7200
    - name: Setup AWS credentials for Nix
      if: ${{ inputs.push-to-cache == 'true' }}
      shell: bash
      run: |
        sudo -H aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        sudo -H aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        sudo -H aws configure set aws_session_token $AWS_SESSION_TOKEN
        sudo -H aws configure set region ${{ inputs.aws-region }}
        sudo mkdir -p /etc/nix
        sudo -E python -c "import os; file = open('/etc/nix/nix-secret-key', 'w'); file.write(os.environ['NIX_SIGN_SECRET_KEY']); file.close()"
        cat << 'EOF' | sudo tee /etc/nix/upload-to-cache.sh > /dev/null
        #!/usr/bin/env bash
        set -euo pipefail
        set -f

        export IFS=' '
        /nix/var/nix/profiles/default/bin/nix copy --max-jobs 5 --to 's3://nix-postgres-artifacts?secret-key=/etc/nix/nix-secret-key' $OUT_PATHS
        EOF
        sudo chmod +x /etc/nix/upload-to-cache.sh
      env:
        NIX_SIGN_SECRET_KEY: ${{ env.NIX_SIGN_SECRET_KEY }}
    - uses: NixOS/nix-installer-action@d6ef7ecd8f685af89869e5aca0580a33e3e3150c
      with:
        installer-version: 2.33.2
        extra-conf: |
          substituters = https://cache.nixos.org https://nix-postgres-artifacts.s3.amazonaws.com
          trusted-public-keys = nix-postgres-artifacts:dGZlQOvKcNEjvT7QEAJbcV6b6uk7VF/hWMjhYleiaLI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          ${{ inputs.push-to-cache == 'true' && 'post-build-hook = /etc/nix/upload-to-cache.sh' || '' }}
          max-jobs = 4
